name: Docker Custom Image CI
run-name: Build ${{ github.ref_name }} - ${{ github.actor }}

on:
  push:
    branches:
      - chs
    tags:
      - '*chs' # 只匹配以 chs 结尾的 tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取全部历史和 tag 信息

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: ./docker/images/n8n/Dockerfile
          build-args: |
            N8N_RELEASE_TYPE=production
          platforms: linux/amd64
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/n8n:${{ github.ref_name }}
